-   id: fmt
    name: fmt
    description: Format files with rustfmt.
    entry: rustfmt --
    language: system
    files: \.rs$
    args: []
-   id: cargo-check
    name: cargo check
    description: Check the package for errors.
    entry: cargo check
    language: system
    files: \.rs$
    pass_filenames: false
-   id: clippy
    name: clippy
    description: Catch common mistakes and improve your Rust code.
    entry: cargo clippy
    language: system
    files: \.rs$
    pass_filenames: false
